### ISSUE TITLE
How to get files send with ajax from objective-php ?

### ISSUE THREAD

**Issue by hasibskrijelj** [objective-php/router#3]
My class extends from AjaxAction

When I do this
      `    $this->getParams()->fromPost()`
it returns an object with my values from my form (so its working)

But when I do this
      `    $this->getParams()->fromFiles()`
it returns NULL

Can someone help me to solve this issue?

ps: I don't want to use the super global $_FILES

Thanks in advance

**Comment by gauthier** [comment]
hi @skrijeljhasib ; as a matter of fact, $_FILEs is not yet wrapped to the request. I'll manage to add it as soon as possible, but this means you'll have to depend on the latest objective-php/application package (actually, parameters aren't handled by the router but by the application directly).

**Comment by hasibskrijelj** [comment]
@gauthier Thanks for your reply :)
