### ISSUE TITLE
How to get $_SERVER values

### ISSUE THREAD

**Issue by Fowerld** [objective-php/router#4]
Similar to this issue: https://github.com/objective-php/router/issues/3.

As Mathieu Hecker asked us in a PR is there a way to get $_SERVER values just like for the post ?
 (Post example: `$this->getParams()->fromPost()`).

Thanks to you

Regards.

**Comment by gauthier** [comment]
Hi @Fowerld, I'm not sure $_SERVER variable content should be injected in the Request. And by the way, it is usually quite a bad idea to rely on whatever lays in this variable into your application :)

Anyway, maybe the more appropriate way to expose these values would be through the existing "env" params using `$this->getParams()->fromEnv()`. What do you think?
