### ISSUE TITLE
Issue with CliRouter in MetaRouter

### ISSUE THREAD

**Issue by WitPxxl** [objective-php/router#5]
Since the commit https://github.com/objective-php/router/commit/e5dc6874c3e51c412c32e534430b6457c23f2fd6 i have an issue with the CliRouter in MetaRouter.

When we retrieve parameter with ```$app->getRequest()->getParameters()```, the CliParameterContainer doesn't have the method setRoute().

**Comment by gauthier** [comment]
Fixed in `objective-php/router` v1.0.2
